// MIT License
//
// Copyright (c) 2026 Cedric Gegout
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

use serde::{Deserialize, Serialize};

/// Standard message role and content pair for chat API payloads.
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct ChatCompletionMessage {
    /// Role identifier (e.g. "system", "user", "assistant").
    pub role: String,

    /// Content string payload.
    pub content: String,
}

/// Incoming completions request conforming to the OpenAI Chat Completion schema.
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct ChatCompletionRequest {
    /// Target model identifier (e.g. "halc").
    pub model: String,

    /// Historical context and input queries.
    pub messages: Vec<ChatCompletionMessage>,

    /// Sampling temperature value.
    pub temperature: Option<f32>,

    /// Maximum count of generated response tokens.
    pub max_tokens: Option<u32>,

    /// Stream chunks flag (unsupported for now, defaults to false).
    #[serde(default)]
    pub stream: bool,
}

/// Representation of a single choices item inside chat responses.
#[derive(Debug, Serialize, Clone)]
pub struct ChatCompletionChoice {
    /// Choices index position.
    pub index: usize,

    /// Output assistant response message.
    pub message: ChatCompletionMessage,

    /// Reason for ending completion (e.g. "stop", "length").
    pub finish_reason: String,
}

/// Token usage tracking metrics.
#[derive(Debug, Serialize, Clone)]
pub struct ChatCompletionUsage {
    /// Prompt tokens count.
    pub prompt_tokens: u32,

    /// Completed response choices tokens count.
    pub completion_tokens: u32,

    /// Cumulative sum of request tokens.
    pub total_tokens: u32,
}

/// Response payload conforming to the OpenAI Chat Completion response schema.
#[derive(Debug, Serialize, Clone)]
pub struct ChatCompletionResponse {
    /// Unique completion identifier.
    pub id: String,

    /// Object wrapper description ("chat.completion").
    pub object: String,

    /// Generation epoch timestamp.
    pub created: i64,

    /// Model name.
    pub model: String,

    /// Choices array containing generated outputs.
    pub choices: Vec<ChatCompletionChoice>,

    /// Token usage metrics.
    pub usage: ChatCompletionUsage,
}

/// Details of a single exposed LLM model.
#[derive(Debug, Serialize, Clone)]
pub struct ModelResponse {
    /// Model identifier.
    pub id: String,

    /// Object descriptor ("model").
    pub object: String,

    /// Creation epoch timestamp.
    pub created: i64,

    /// Owner organization or project.
    pub owned_by: String,
}

/// List of models container payload.
#[derive(Debug, Serialize, Clone)]
pub struct ModelListResponse {
    /// Object descriptor ("list").
    pub object: String,

    /// Array of models.
    pub data: Vec<ModelResponse>,
}

/// Single entry mapping an agent to its aggregated peer review score.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ScoreTableEntry {
    /// Agent identifier.
    pub agent: String,

    /// Cumulative points scored.
    pub value: i32,
}

/// Final decision payload generated by the confrontation loop.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct Decision {
    /// The selected winning agent's name.
    pub winning_agent: String,

    /// Sum of challenges score achieved by the winning agent.
    pub winning_score: i32,

    /// Full proposal content of the winner.
    pub proposal: String,

    /// Rationale for selecting this proposal.
    pub rationale: String,

    /// Known risks associated with the winning proposal.
    pub risks: Vec<String>,

    /// Full score details table.
    pub score_table: Vec<ScoreTableEntry>,

    /// The generated final decision markdown content.
    #[serde(default)]
    pub markdown: String,
}
